export const images = {
  // Logo: require("Assets/Images/Logo.svg"),
  Logo: require("Assets/Images/Pulse-Logo.svg"),
  MenuColleps: require("Assets/Images/ExpandArrow.svg"),
  SearchIcon: require("Assets/Images/SearchIcon.svg"),
  UserPhoto: require("Assets/Images/UserPhoto.png"),
  DownArrowOne: require("Assets/Images/DownArrowOne.svg"),
  Notification: require("Assets/Images/Notification.svg"),
  Plus: require("Assets/Images/Plus.svg"),
  Send: require("Assets/Images/send.svg"),
  PrevieServey: require("Assets/Images/preview-survey.png"),
  Alert: require("Assets/Images/alert.svg"),
  Awful: require("Assets/Images/awful.svg"),
  ReallyGood: require("Assets/Images/reallygood.svg"),
  Fantastic: require("Assets/Images/fantastic.svg"),
  Okay: require("Assets/Images/okay.svg"),
  NotGood: require("Assets/Images/notverygood.svg"),
  beaconsImages: require("Assets/Images/beacons-images.svg"),
  pulseAppIcon: require("Assets/Images/pulse-app-icon.svg"),
  DownArrow: require("Assets/Images/down-arrow.svg"),
  beaconIcon: require("Assets/Images/beacon-icon.svg"),
  BeaconUuid: require("Assets/Images/beacon-uuid.svg"),
  DefaultAvatar: require("Assets/Images/defaultuser.svg"),
  NoBecaon: require("Assets/Images/NoBeacon.svg"),
  NoCampaign: require("Assets/Images/NoCampaign.svg"),
  NoUser: require("Assets/Images/NoUser.svg"),
  // NoCampaign: require("Assets/Images/NoUser.svg"),
  ProfilePhoto: require("Assets/Images/ProfilePhoto.png"),
  IllustrationUpload: require("Assets/Images/IllustrationUpload.svg"),
  UploadProgress: require("Assets/Images/UploadProgress.svg"),
  UserAvatar: require("Assets/Images/UserAvatar.svg"),
  NoLocation: require("Assets/Images/NoLocation.svg")

  // LoginBackground: require("Assets/Images/LoginBackground.png")
};
